### ISSUE TITLE
Repo for other Docker images?

### ISSUE THREAD

**Issue by alex3305** [gjong/docker#2]
Hi,

I saw that you have several other Docker images in your [Docker Hub repo](https://hub.docker.com/u/gjong), can you also provide the Docker images on those repo's? 

Additional question is that I saw that these are hass.io images. I would love to add these images through the hass.io repository, if possible.

**Comment by alex3305** [comment]
@gjong Any chance you had any time to look at this?

**Comment by gjong** [comment]
@alex3305 sorry for the late reply, I don't check github that frequently any more. Most of the other docker images come from bitbucket repositories. If the Dockerfile is not in the docker hub it is build using circleci. There all under https://bitbucket.org/jongsoftdev/
